-- USER_INFO 테이블과 ONLINE_SALE 테이블에서 년, 월, 성별 별로 상품을 구매한 회원수를 집계
-- 결과는 년, 월, 성별을 기준으로 오름차순 정렬
-- 이때, 성별 정보가 없는 경우 결과에서 제외해주세요.


# SELECT 
#     YEAR(OS.SALES_DATE) AS YEAR, 
#     MONTH(OS.SALES_DATE) AS MONTH, 
#     UI.GENDER, 
#     COUNT(OS.USER_ID) AS USERS
# FROM USER_INFO UI JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
# GROUP BY YEAR(OS.SALES_DATE)
# HAVING COUNT(UI.GENDER) > 0
# ORDER OS.YEAR, OS.MONTH, UI.GENDER;

SELECT 
    YEAR(OS.SALES_DATE) AS YEAR, 
    MONTH(OS.SALES_DATE) AS MONTH, 
    UI.GENDER,
    COUNT(DISTINCT OS.USER_ID) AS USERS
FROM USER_INFO UI JOIN ONLINE_SALE OS 
    ON UI.USER_ID = OS.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY 
    YEAR(OS.SALES_DATE), 
    MONTH(OS.SALES_DATE), 
    UI.GENDER
ORDER BY YEAR, MONTH, UI.GENDER;