-- 각 세대별 자식이 없는 개체의 수(COUNT)와 세대(GENERATION)를 출력
-- 결과는 세대에 대해 오름차순 정렬
-- 모든 세대에는 자식이 없는 개체가 적어도 1개체는 존재
WITH RECURSIVE GH AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GH G ON E.PARENT_ID = G.ID
)
SELECT COUNT(G.ID) AS COUNT, G.GENERATION
FROM GH G
LEFT JOIN ECOLI_DATA C ON G.ID = C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION;
