-- 코드를 작성해주세요
# SELECT ID, GENOTYPE, PARENT_GENOTYPE
# FROM ECOLI_DATA
# WHERE PARENT_GENOTYPE = (SELECT GENOTYPE FROM ECOLI_DATA WHERE GENOTYPE & 1 )
# ORDER BY ID;

SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA A, ECOLI_DATA B
WHERE A.PARENT_ID = B.ID
AND B.GENOTYPE & A.GENOTYPE = B.GENOTYPE
ORDER BY ID;