-- 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지총 대여 횟수가 5회 이상인 자동차들
-- 해당 기간 동안의 월별 자동차 ID별 총 대여 횟수(컬럼명: RECORDS) 리스트를 출력
-- 결과는 월을 기준으로 오름차순 정렬하고, 월이 같다면 자동차 ID를 기준으로 내림차순 정렬
-- 특정 월의 총 대여 횟수가 0인 경우에는 결과에서 제외

# SELECT MONTH(START_DATE) AS MONTH, SBQR.CAR_ID, COUNT(CAR_ID) AS RECORDS
# FROM (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
#     GROUP BY CAR_ID
#     HAVING COUNT(CAR_ID) >= 5
# ) SBQR
# ORDER BY MONTH ASC, SBQR.CAR_ID DESC;

-- SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE CAR_ID = 1;

SELECT 
    MONTH(RH.START_DATE) AS MONTH,
    RH.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022 
      AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AS SBQR 
  ON RH.CAR_ID = SBQR.CAR_ID
WHERE YEAR(RH.START_DATE) = 2022
  AND MONTH(RH.START_DATE) BETWEEN 8 AND 10
GROUP BY 
    MONTH(RH.START_DATE),
    RH.CAR_ID
ORDER BY 
    MONTH(RH.START_DATE) ASC,
    RH.CAR_ID DESC;
