-- 물고기 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이를 출력
-- AS ID, AS FISH_NAME, AS LENGTH
-- 결과는 물고기의 ID에 대해 오름차순 정렬
WITH RANKED_FISH AS (
    SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH,
        RANK() OVER (PARTITION BY FI.FISH_TYPE ORDER BY FI.LENGTH DESC) AS RANK_NUM
    FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH
FROM RANKED_FISH
WHERE RANK_NUM = 1
ORDER BY ID;

